In [211]:
# %matplotlib inline
import numpy as np

In [212]:
x = np.array(([3,5], [5,1], [10,2]), dtype=float)
y = np.array(([75], [82], [93]), dtype=float)


In [213]:
x = x/np.amax(x, axis=0)
y = y/100


In [214]:
# y

In [215]:
# x.shape

In [216]:
class Neural_Network(object):
    def __init__(self):
        self.inputLayerSize = 2
        self.outputLayerSize=1
        self.hiddenLayerSize=3

        #weights
        self.w1 = np.random.rand(self.inputLayerSize,self.hiddenLayerSize)
        self.w2 = np.random.rand(self.hiddenLayerSize,self.outputLayerSize)

        # print(self.w2)

    def forward(self,x):
        self.z2= np.dot(x,self.w1)
        self.a2= self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.w2)
        yHat = self.sigmoid(self.z3)
        return yHat
            
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z)) 

    def sigmoidPrime(self,z):
        #Gradient of sigmoid
        return np.exp(-z)/((1+np.exp(-z))**2)

    def costFunction(self,x,y):
        self.yhat = self.forward(x)
        J=0.5*sum((y-self.yhat)**2)
        return J

    def costFunctionPrime(self, x, y):
        #Compute derivative with respect to W and W2 for a given X and y:
        self.yHat = self.forward(x)
        
        delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
        dJdW2 = np.dot(self.a2.T, delta3)
        
        delta2 = np.dot(delta3, self.w2.T)*self.sigmoidPrime(self.z2)
        dJdW1 = np.dot(x.T, delta2)  
        
        return dJdW1, dJdW2
      

In [217]:
NN = Neural_Network()

In [218]:
cost1 = NN.costFunction(x,y)

In [219]:
NN.w1

array([[0.70822612, 0.92149652, 0.66510626],
       [0.91909985, 0.62325698, 0.54155126]])

In [220]:
scalar = 3
dJdW1, dJdW2 = NN.costFunctionPrime(x,y)
NN.w1 = NN.w1 - scalar*dJdW1
NN.w2 = NN.w2 - scalar*dJdW2
cost2 = NN.costFunction(x, y)

In [221]:
dJdW1

array([[-0.0036103 , -0.00298965, -0.00736444],
       [-0.00156905, -0.00131547, -0.0032269 ]])

In [223]:
scalar*dJdW1

array([[-0.01083089, -0.00896895, -0.02209333],
       [-0.00470716, -0.00394642, -0.00968071]])

In [222]:
print(cost1,cost2)
NN.w1

[0.0223257] [0.01157597]


array([[0.71905701, 0.93046547, 0.68719959],
       [0.92380701, 0.62720341, 0.55123197]])